name: getx_lego
description: "apply getx in flutter with lego project"
#publish_to: 'none'
repository: https://github.com/flutter-lego/getx_lego

version: 1.0.3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  get: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  widget_binding_lego: #@add

flutter:
  assets:
    - assets/lego/getx_lego/
  uses-material-design: true

topics:
  - lego